# 导入基础配置include ../redis-default.conf
# 根目录,建议配置成绝对路径,这样下面的file都可以配置成相对路径
dir /home/redis
# 守护方式启动
daemonize yes
# 守护方式PID存放路径
pidfile run/redis_6379.pid
# 启动端口
port 6379
# tcp队列长度(不能超过somaxconn和tcp_max_syn_backlog的值)
tcp-backlog 4096
# 绑定的客户端地址
bind 0.0.0.0
# 客户端闲置关闭时间,0代表不关闭
timeout 300
# 检测时间,空闲则关闭
tcp-keepalive 60
# 日志级别 debug/verbose:适用于开发和调试 notice:适用于生产模式 warning:只打印警告
loglevel notice
# 日志文件stdout是标准输出(输出屏幕或者发送给dev/null)
# logfile "log/redis_6379.log"
logfile stdout
# 数据库访问密码(由外界命令配置)
# requirepass M5Pi9YW6u
# 最大连接数 0代表不限制
maxclients 0
# 最大内存限制maxmemory bytes
# maxmemory 16777216
# 开启RDB 每60分钟备份一次
save 3600 1
# 开启AOF
appendonly yes
# AOF文件位置
appendfilename "appendonly.aof"
# 每秒备份
appendfsync everysec
# 开启混合备份模式
aof-use-rdb-preamble yes
# 混合模式RDB备份时机 ,默认是文件到达64M即进行重写
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 128mb

# 禁用危险命令
rename-command FLUSHALL "nkGqnnmrnES22sA0KI9KVP18TToAhbwP"
rename-command FLUSHDB "3h0Y2uVnENarfbF8tHtVrP4Q1PUXZnU8"
rename-command KEYS "Rq1iyHHsPfUam9w9XkBQ5mhRERI01YIs"
rename-command CONFIG "9jgj3ETHylbxczuJT6Kp6GSHuNdJB1xd"