# 数据库校验- mysql
database:
  host: 'localhost'
  port: 3306
  user: 'root'
  # 不用''会被解析成int类型数据
  password: 'PassWord@MySql123'
  name: 'pika'
  charset: utf8mb4
  time_zone: 'Asia/Shanghai'

# Redis配置
redis:
  host: 'localhost'
  enable_flag: Ture
  port: 6379
  auth: 'PassWord@Redis123'
  encoding: "utf-8"
  index: 0
  decode_responses: True  # 获取中文数据可以直接 decode python unicode
  target_max_memory: '572978192'
  max_connections: 100

email:
  # 发件人邮箱
  sender: "501893067@qq.com"
  # 发件人邮箱授权码
  password: "gzekixviowwvbhha"
  # 邮箱host
  host: "smtp.qq.com"
  # 端口号
  "port": 465
  # to
  "to": ""

jwt:
  secret_key: "cvaEjaD2qcMgAtX9uLLHQnZHaD7pxt9wS3nmCcrCfXVwz6csBQn27Y8S5Q9"
  md5_salt: "EjZHaD7pxt9z6csBQn27Y8S5Q9"
  mpop: False


oss:
  type: "aliyun"
  access_key_id: "W1Phi9Ysh7Wn3"
  access_key_secret: "Isw76Fc9Ix71X0Azb5Pc1Wcd1Pf1F39Gxs5Kjt5Bt"
  bucket_name: ""
  endpoint: ""

other:
  # 日志开关
  log_switch: True

yapi:
  access_key: ""
  secret_key: ""

github:
  user_info_url: "https://api.github.com/user"
  access_token_url: "https://github.com/login/oauth/access_token"
  client_id: ""
  access_key: ""
  secret_key: ""

mitmproxy:
  port: 7781
  enable_flag: True

case:
  retry_times: 1