version: "3.3"
services:
  pika:
    build:
      context: .
      dockerfile: docker-images/Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        uvicorn Application:app --host 0.0.0.0 --port 7780 --reload