site_name: FastAPI
site_description: FastAPI framework, high performance, easy to learn, fast to code, ready for production
site_url: https://fastapi.tiangolo.com/zh/
theme:
  name: material
  custom_dir: overrides
  palette:
  - scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  - scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  logo: https://fastapi.tiangolo.com/img/icon-white.svg
  favicon: https://fastapi.tiangolo.com/img/favicon.png
  language: zh
repo_name: tiangolo/fastapi
repo_url: https://github.com/tiangolo/fastapi
edit_uri: ''
plugins:
- search
- markdownextradata:
    data: data
nav:
- FastAPI: index.md
- Languages:
  - zh: /zh/
- features.md
- fastapi-people.md
- python-types.md
- 教程 - 用户指南:
  - tutorial/index.md
  - tutorial/first-steps.md
  - tutorial/path-params.md
  - tutorial/query-params.md
  - tutorial/body.md
  - tutorial/query-params-str-validations.md
  - tutorial/path-params-numeric-validations.md
  - tutorial/body-multiple-params.md
  - tutorial/body-fields.md
  - tutorial/middleware.md
  - tutorial/body-nested-models.md
  - tutorial/header-params.md
  - tutorial/response-model.md
  - tutorial/extra-models.md
  - tutorial/response-status-code.md
  - tutorial/schema-extra-example.md
  - tutorial/extra-data-types.md
  - tutorial/cookie-params.md
  - tutorial/request-forms.md
  - tutorial/request-files.md
  - tutorial/request-forms-and-files.md
  - tutorial/handling-errors.md
  - tutorial/body-updates.md
  - 依赖项:
    - tutorial/dependencies/index.md
    - tutorial/dependencies/sub-dependencies.md
    - tutorial/dependencies/dependencies-in-path-operation-decorators.md
    - tutorial/dependencies/global-dependencies.md
  - 安全性:
    - tutorial/security/index.md
    - tutorial/security/get-current-user.md
    - tutorial/security/simple-oauth2.md
    - tutorial/security/oauth2-jwt.md
  - tutorial/cors.md
  - tutorial/bigger-applications.md
  - tutorial/metadata.md
  - tutorial/debugging.md
- 高级用户指南:
  - advanced/index.md
  - advanced/path-operation-advanced-configuration.md
  - advanced/additional-status-codes.md
  - advanced/response-directly.md
  - advanced/custom-response.md
- deployment.md
- contributing.md
- help-fastapi.md
- benchmarks.md
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- mdx_include:
    base_path: docs
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed
extra:
  alternate:
  - link: /zh/
    name: zh - 汉语
extra_css:
- https://fastapi.tiangolo.com/css/termynal.css
- https://fastapi.tiangolo.com/css/custom.css
extra_javascript:
- https://fastapi.tiangolo.com/js/termynal.js
- https://fastapi.tiangolo.com/js/custom.js
