version: "3"
services:
  pika:
    image: kamalyes/pika-testing:latest
    container_name: pika
    restart: always
    privileged: true 
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${WORKSPACES_PATH}/conf:/opt/pika/conf
      - ${WORKSPACES_PATH}/logs:/opt/pika/logs
    networks:
      pika-network:
        aliases:
          - pika_server