version: "2.1"
services:
  mysql:
    image: mysql:${PIKA_MYSQL_VERSION}
    container_name: mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p${PIKA_MYSQL_PASSWORD}"
        ]
      interval: 6s
      timeout: 5s
      retries: 50
    environment:
      MYSQL_DATABASE: ${PIKA_MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${PIKA_MYSQL_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - ${PIKA_BASE}/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ${PIKA_BASE}/bin/mysql:/docker-entrypoint-initdb.d/
      - pika-mysql-data:/var/lib/mysql
    networks:
      - pika-network
    restart: always
  system-setting:
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  pika-mysql-data:
    driver_opts:
      type: none
      device: ${PIKA_BASE}/data/mysql
      o: bind
