version: "2.1"
services:
  redis:
    image: redis:${PIKA_REDIS_VERSION}
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 6s
      timeout: 5s
      retries: 50
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - ${PIKA_REDIS_PORT}:6379
    volumes:
      - ${PIKA_BASE}/conf/redis.conf:/etc/redis/redis.conf
      - pika-redis-data:/data
    command: redis-server /etc/redis/redis.conf --requirepass ${PIKA_REDIS_PASSWORD}
    networks:
      - pika-network
    restart: always
  system-setting:
    depends_on:
      redis:
        condition: service_healthy

volumes:
  pika-redis-data:
    driver_opts:
      type: none
      device: ${PIKA_BASE}/data/redis
      o: bind
