# 基础配置
## 安装路径, Pika 配置及数据文件默认将安装在 ${PIKA_BASE} 目录下
PIKA_BASE=/opt/pika
## Pika 使用的 docker 网络网段信息
PIKA_DOCKER_SUBNET=172.30.10.0/24
## 镜像前缀, Pika 相关组件使用的 Docker 镜像前缀
PIKA_IMAGE_PREFIX='kamalyes/pika-testing'
## 镜像标签, Pika 相关组件使用的 Docker 镜像标签
PIKA_IMAGE_TAG=latest
## 安装模式
PIKA_INSTALL_MODE=allinone
## Pika 主程序的 HTTP 服务监听端口
PIKA_SERVER_PORT=8081
## Pika Node-Controller 组件的 HTTP 服务监听端口
PIKA_NODE_CONTROLLER_PORT=8082
PIKA_NODEEXPORTER_PORT=9100

# 数据库配置
## 是否使用外部数据库
PIKA_EXTERNAL_MYSQL=false
PIKA_MYSQL_VERSION = 8.0.30
## 数据库地址
PIKA_MYSQL_HOST=mysql
## 数据库端口
PIKA_MYSQL_PORT=3306
## 数据库库名
PIKA_MYSQL_DB=Pika
## 数据库用户名
PIKA_MYSQL_USER=root
## 数据库密码
PIKA_MYSQL_PASSWORD=Password123@mysql

# Redis 配置
## 是否使用外部Redis
PIKA_EXTERNAL_REDIS=false
PIKA_REDIS_VERSION = redis:7.0.8-alpine
## Redis 端口
PIKA_REDIS_PORT=6379
## Redis 密码
PIKA_REDIS_PASSWORD=Password123@redis
## Redis地址
PIKA_REDIS_HOST=$(hostname -I | cut -d" " -f 1)