# 拉取python 3.9-slim 版本镜像
FROM python:3.9-slim as builder
ENV WORKSPACES /opt/pika
RUN mkdir -p ${WORKSPACES}
WORKDIR ${WORKSPACES}
COPY ./requirements.txt ./requirements.txt
RUN python -m venv ${WORKSPACES}/venv  \
    && ${WORKSPACES}/venv/bin/python -m pip install --upgrade pip \
    && ${WORKSPACES}/venv/bin/python -m pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ \
    && apt update -y \
    && apt upgrade -y \
    && apt install -y wget \
    && apt install -y vim \
    && apt install -y curl \
    && apt install -y tzdata \
    && wget https://github.com/vishnubob/wait-for-it/raw/master/wait-for-it.sh


FROM python:3.9-slim
ENV PYTHONUNBUFFERED=1
ENV WORKSPACES /opt/pika
WORKDIR ${WORKSPACES}
COPY . .
COPY --from=builder ${WORKSPACES}/venv/ ${WORKSPACES}/venv/
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
COPY --from=builder ${WORKSPACES}/wait-for-it.sh ${WORKSPACES}/ops/wait-for-it.sh
RUN ln -sf ${WORKSPACES}/ops/dev.env.ops ${WORKSPACES}/conf/dev.env \
    && chmod +x ${WORKSPACES}/ops/wait-for-it.sh

EXPOSE 7777

CMD ["${WORKSPACES}/venv/bin/supervisord", "-c", "${WORKSPACES}/ops/supervisor.conf"]
