name: Install Require
on:
  push:
    branches:
      - ssh-service # 只在ssh-service上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE
jobs:

  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@ssh-service

      - name: copy file via ssh password
        uses: appleboy/scp-action@ssh-service
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "*"
          target: "/opt/pika"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@ssh-service
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /opt/pika && pip3 install -r requirements.txt --user && pkill gunicorn
